name: Main PRs CI

on:
  pull_request:
    branches: [ main ]

jobs:
  running-tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: mdillon/postgis
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [ 20.x ]
        redis-version: [ 6 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install postgresql client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - run: npm i

      - run: npx sequelize-cli db:create;

      - name: Install postgis
        run: psql -h 127.0.0.1 --port 5432 -U postgres realtime-conversation-api-test --command "CREATE EXTENSION postgis"
        env:
          PGPASSWORD: postgres

      - name: Install MongoDB client
        run: sudo apt-get install mongodb-clients

      - name: Create a database and collection
        run: |
          mongo localhost:27017/realtime-conversation --eval "db.createCollection('dummy')"

      - run: npx ts-node src/db/test/init_test_db.ts;
      - run: npx sequelize-cli db:seed:all;

      - run: npm run test:github
